.PHONY:
	hello
	err

hello:
	# this is a comment
	python -c "print('hello world')"

err:
	keyboardmashitalltogetherthisshouldnotrunotherwiseunittestswillfail

circle:
	# of life
	circle

empty:
	# head

one:
	@make two

two:
	@+make empty
	@+make three

three:
	@+make circle
