name: Test
on:
  push:
  pull_request:
  schedule: [{cron: '2 3 * * 6'}]  # M H d m w (Sat 3:02)
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    permissions: {contents: write, id-token: write, packages: write}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN || github.token }}
    - uses: actions/setup-python@v5
      with: {python-version: '3.x'}
    - uses: mxschmitt/action-tmate@v3
    - id: dist
      uses: casperdcl/deploy-pypi@trusted-pub
      with:
        build: true
        upload: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
    - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      name: Release
      run: |
        changelog=$(git log --pretty='format:%d%n- %s%n%b---' $(git tag --sort=v:refname | tail -n2 | head -n1)..HEAD)
        tag="${GITHUB_REF#refs/tags/}"
        gh release create --title "py-make $tag stable" --draft --notes "$changelog" "$tag" dist/${{ steps.dist.outputs.whl }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
